CREATE TABLE [dbo].[FieldDefinitions] (
    [Id]              [uniqueidentifier] NOT NULL CONSTRAINT [DF_FieldDefinitions_Id] DEFAULT (newsequentialid()),
    [OrganizationId]  [uniqueidentifier] NOT NULL,
    [FieldSectionId]  [uniqueidentifier] NULL,
    [FieldKey]        [nvarchar](100)    NOT NULL,
    [FieldLabel]      [nvarchar](200)    NOT NULL,
    [FieldType]       [nvarchar](20)     NOT NULL,
    [PlaceHolderText] [nvarchar](200)    NULL,
    [HelpText]        [nvarchar](500)    NULL,
    [IsRequired]      [bit]              NOT NULL CONSTRAINT [DF_FieldDefinitions_IsRequired] DEFAULT (0),
    [IsActive]        [bit]              NOT NULL CONSTRAINT [DF_FieldDefinitions_IsActive] DEFAULT (1),
    [DsiplayOrder]    [int]              NOT NULL CONSTRAINT [DF_FieldDefinitions_DsiplayOrder] DEFAULT (0),
    [MinValue]        [decimal](18, 4)   NULL,
    [MaxValue]        [decimal](18, 4)   NULL,
    [MinLength]       [int]              NULL,
    [MaxLength]       [int]              NULL,
    [RegExPattern]    [nvarchar](500)    NULL,
    [CreatedDt]       [datetime]         NOT NULL CONSTRAINT [DF_FieldDefinitions_CreatedDt] DEFAULT (getutcdate()),
    [ModifiedDt]      [datetime]         NOT NULL CONSTRAINT [DF_FieldDefinitions_ModifiedDt] DEFAULT (getutcdate()),

    CONSTRAINT [PK_FieldDefinitions] PRIMARY KEY CLUSTERED ([Id]),
    CONSTRAINT [FK_FieldDefinitions_Organizations] FOREIGN KEY ([OrganizationId]) REFERENCES [dbo].[Organizations] ([Id]),
    CONSTRAINT [FK_FieldDefinitions_FieldSections]  FOREIGN KEY ([FieldSectionId])  REFERENCES [dbo].[FieldSections] ([Id]),
    CONSTRAINT [UQ_FieldDefinitions_Key] UNIQUE ([OrganizationId], [FieldKey]),
    CONSTRAINT [CK_FieldDefinitions_Type] CHECK ([FieldType] IN ('text', 'number', 'date', 'datetime', 'checkbox', 'dropdown', 'multiselect'))
);
